name: eduhub
description: "A modern, scalable EdTech Flutter application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: any
  state_notifier: ^1.0.0
  dio: ^5.9.0
  go_router: ^17.0.0
  freezed_annotation: any
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  fpdart: ^1.2.0
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any
  riverpod_generator: any
  json_serializable: any
  freezed: any
  mockito: any
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
